### ISSUE TITLE
Using domain class in SecurityConfig.groovy

### ISSUE THREAD

**Issue by cheikhTSeck** [dynamind/grails3-spring-security-keycloak-minimal#2]
Hi everyone,
i'm trying to secure my application using urls and roles defined in domain class but i have an error with GORM not being initialised.
Thanks

**Comment by dynamind** [comment]
I've removed all Hibernate/GORM stuff that is part of the default `grails create-app` result (to achieve the "minimal" setup I intended). You can check `build.gradle` to add the required dependencies back in.

**Comment by cheikhTSeck** [comment]
Thank you Mr. Willemse for your reactivity but even if i add theses dependencies, it doesn't work. I cannot have access to an hibernate session to get data from the database.
Is it possible to use grails spring security core plugin with keycloak plugin instead of the embedded one to have access to the requestmap?

**Comment by dynamind** [comment]
Ah yes, you'll probably want to drop the current method of http security configuration because it is one-time configuration during startup, unless that's exactly what you want. The grails spring security core plugin has been designed with GORM in mind, so you may prefer using that instead of the bare bones Spring-Boot-y method I used here.
